
#FOR IG and FB
FB_PAGE_ACCESS_TOKEN = "{YOUR_FB_PAGE_ACCESS_TOKEN}"
IG_BUSINESS_ID = "{YOUR_IG_BUSINESS_ID}"
DIRECTORY_IG = "~"
DIRECTORY_FB = "~"
PAGE_ID = "{FB_PAGE_ID}"
SEARCH_CRITERIA = "{YOUR_SEARCH_CRITERIA}"
TIME_CRITERIA = '2026'

#YOUTUBE BELOW
YT_API_KEY = "{YOUR_API_KEY}"
YT_CHANNEL_ID = "{YOUR_CHANNEL_ID}"
DIRECTORY_YT = "{YOUR_DIRECTORY}"
