#FOR IG and FB
PAGE_ACCESS_TOKEN = "{YOUR_PAGE_ACCESS_TOKEN}"
IG_BUS_ID = "{YOUR_IG_BUSINESS_ID}"
DIRECTORY_IG = "{YOUR_DIRECTORY}"
DIRECTORY_FB = "{YOUR_DIRECTORY}"
PAGE_ID = "{FB_PAGE_ID}"
SEARCH_CRITERIA = "{YOUR_SEARCH_CRITERIA}"
TIME_CRITERIA = '2026'

#YOUTUBE BELOW
API_KEY = "{YOUR_API_KEY}"
CHANNEL_ID = "{YOUR_CHANNEL_ID}"
DIRECTORY_YT = "{YOUR_DIRECTORY}"
